extends Node

enum Style {BASIC, COWBOY, ENGLISH, BASEBALL, BEANIE, STRAW}
enum State {DEFAULT, FISHING, BUILDING, SHOP}
enum Tool {AXE, HOE, SWORD, WATER, FISH, SEED, PICKAXE}
enum Machine {SPRINKLER, FISHER, SCARECROW, DELETE}
enum Seed {TOMATO, CORN, PUMPKIN, WHEAT, ORANGE, LEMON, LIME, BANANA, PEAR, APRICOT, MANGO, GUAVA}
enum Item {WOOD, APPLE, TOMATO, CORN, WHEAT, PUMPKIN, FISH, STONE, IRON, GOLD, SILVER, PLATINUM, DIAMOND, RUBY, SAPPHIRE, EMERALD, SUNFISH, CRAPPIE, SMALLMOUTH_BASS, LARGEMOUTH_BASS, PIKE, MUSKIE, CATFISH, CARP, ORANGE_FRUIT, LEMON_FRUIT, LIME_FRUIT, BANANA_FRUIT, PEAR_FRUIT, APRICOT_FRUIT, MANGO_FRUIT, GUAVA_FRUIT, ORANGE_SEED, LEMON_SEED, LIME_SEED, BANANA_SEED, PEAR_SEED, APRICOT_SEED, MANGO_SEED, GUAVA_SEED}
enum Shop {MAIN, HAT}
